- name: CloudForms OpenShift Quota Projects Parameters
  block:
  - set_fact:
      openshift_quota_projects_yaml: '{{ openshift_quota_projects_cfme | from_yaml }}'
  - set_fact:
      openshift_quota_projects: '{{ openshift_quota_projects_yaml.openshift_quota_projects}}'
  when: openshift_quota_projects_cfme is defined

- name: CloudForms OpenShift Quota Projects Excluder Parameters
  block:
  - set_fact:
      openshift_quota_projects_excluder_yaml: '{{ openshift_quota_projects_excluder_cfme | from_yaml }}'
  - set_fact:
      openshift_quota_projects_excluder: '{{ openshift_quota_projects_excluder_yaml.openshift_quota_projects_excluder}}'
  when: openshift_quota_projects_excluder_cfme is defined